project:
  type: website
  output-dir: docs

website:
  title: "Abhay Partap Thakur"
  search: false
  navbar: false

format:
  html:
    theme: cosmo
    toc: false
    smooth-scroll: true
    page-layout: full
    css: styles.css
